port: 8080
debug: true
mysql:
  host: "127.0.0.1"
  port: 3306
  user_name: "root"
  password: "Cy20050823"
  database: "NoteBook"

redis:
  host: '192.168.88.102'
  port: '6379'
  password: "Cy20050823"
  database: 0

jwt:
  secret: '5$!UEmvB#nRB@Iwab#Sy!zofKEOGLRtE'
  expire: 24